# Generated by Django 5.2.6 on 2026-01-25 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Plan Name')),
                ('price_monthly', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monthly Price')),
                ('max_users', models.IntegerField(default=1, verbose_name='Max Users')),
                ('max_storage_gb', models.IntegerField(default=1, verbose_name='Max Storage (GB)')),
                ('features', models.TextField(blank=True, help_text='JSON or comma-separated list', verbose_name='Features')),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
            },
        ),
    ]
