# Generated by Django 5.2.6 on 2026-02-13 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_permission_rolepermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='inn',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='INN'),
        ),
    ]
