# Generated by Django 5.2.6 on 2026-01-27 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('directories', '0005_contactperson'),
        ('registers', '0004_accountingpolicy_goodsintransit'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='Order Number')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('order_type', models.CharField(choices=[('INBOUND', 'Inbound (Приход)'), ('OUTBOUND', 'Outbound (Расход)'), ('TRANSFER', 'Transfer (Перемещение)'), ('ADJUSTMENT', 'Adjustment (Инвентаризация)')], max_length=20, verbose_name='Order Type')),
                ('object_id', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('CREATED', 'Created (Создан)'), ('APPROVED', 'Approved (Утверждён)'), ('IN_PROGRESS', 'In Progress (В работе)'), ('EXECUTED', 'Executed (Исполнен)'), ('CANCELLED', 'Cancelled (Отменён)')], default='CREATED', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_orders_approved', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_orders_created', to=settings.AUTH_USER_MODEL)),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_orders_executed', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_orders', to='directories.warehouse')),
            ],
            options={
                'verbose_name': 'Warehouse Order',
                'verbose_name_plural': 'Warehouse Orders',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_planned', models.DecimalField(decimal_places=3, help_text='From source document', max_digits=15, verbose_name='Planned Quantity')),
                ('quantity_actual', models.DecimalField(decimal_places=3, default=0, help_text='Actually picked/received by warehouse', max_digits=15, verbose_name='Actual Quantity')),
                ('comment', models.CharField(blank=True, help_text='e.g., Damaged, Wrong SKU, etc.', max_length=255, verbose_name='Comment')),
                ('batch', models.ForeignKey(blank=True, help_text='For outbound: which batch was picked', null=True, on_delete=django.db.models.deletion.SET_NULL, to='registers.stockbatch')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directories.item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='warehouse.warehouseorder')),
            ],
            options={
                'verbose_name': 'Warehouse Order Line',
                'verbose_name_plural': 'Warehouse Order Lines',
            },
        ),
        migrations.AddIndex(
            model_name='warehouseorder',
            index=models.Index(fields=['tenant', 'status', 'date'], name='warehouse_w_tenant__c83998_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouseorder',
            index=models.Index(fields=['warehouse', 'status'], name='warehouse_w_warehou_dba678_idx'),
        ),
    ]
