# Generated by Django 5.2.6 on 2026-01-29 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_permission_rolepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='Form Code')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('period_type', models.CharField(choices=[('MONTH', 'Monthly'), ('QUARTER', 'Quarterly'), ('YEAR', 'Yearly')], max_length=20, verbose_name='Period Type')),
            ],
        ),
        migrations.CreateModel(
            name='TaxField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Line Code')),
                ('label', models.CharField(max_length=255, verbose_name='Label')),
                ('source_type', models.CharField(choices=[('LEDGER', 'Ledger Query'), ('FORMULA', 'Formula'), ('MANUAL', 'Manual Input')], max_length=20, verbose_name='Source Type')),
                ('formula', models.TextField(blank=True, help_text='For FORMULA: expression (010+020). For LEDGER: JSON query config.', verbose_name='Formula/Query')),
                ('is_required', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='taxes.taxform')),
            ],
            options={
                'ordering': ['order', 'code'],
                'unique_together': {('form', 'code')},
            },
        ),
        migrations.CreateModel(
            name='TaxReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(verbose_name='Period Start')),
                ('period_end', models.DateField(verbose_name='Period End')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted/Finalized'), ('superseded', 'Superseded')], default='draft', max_length=20)),
                ('snapshot_date', models.DateTimeField(auto_now_add=True, help_text='When this report was generated', verbose_name='Snapshot Date')),
                ('ledger_frozen_at', models.DateTimeField(blank=True, help_text='Timestamp when ledger data was captured', null=True, verbose_name='Ledger Frozen At')),
                ('version', models.IntegerField(default=1, help_text='Report version number')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_by', models.CharField(blank=True, max_length=255)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='taxes.taxform')),
                ('superseded_by', models.ForeignKey(blank=True, help_text='The newer version that replaced this report', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='taxes.taxreport')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_reports', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Tax Report',
                'verbose_name_plural': 'Tax Reports',
                'ordering': ['-period_start', '-version'],
            },
        ),
        migrations.CreateModel(
            name='TaxScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=2, verbose_name='Country Code')),
                ('name', models.CharField(max_length=100, verbose_name='Scheme Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('version', models.CharField(max_length=20, verbose_name='Version')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tax Scheme',
                'verbose_name_plural': 'Tax Schemes',
                'unique_together': {('country', 'name', 'version')},
            },
        ),
        migrations.AddField(
            model_name='taxform',
            name='scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='taxes.taxscheme'),
        ),
        migrations.CreateModel(
            name='TaxReportLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_numeric', models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Value')),
                ('value_text', models.TextField(blank=True, verbose_name='Text Value')),
                ('is_manual_override', models.BooleanField(default=False)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='taxes.taxfield')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='taxes.taxreport')),
            ],
            options={
                'unique_together': {('report', 'field')},
            },
        ),
    ]
