# Generated by Django 5.2.6 on 2026-01-25 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='Contract Number')),
                ('date', models.DateField(verbose_name='Contract Date')),
                ('contract_type', models.CharField(choices=[('SALES', 'Sales Contract'), ('PURCHASE', 'Purchase Contract'), ('COMMISSION', 'Commission Agent')], max_length=20, verbose_name='Type')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Contract',
                'verbose_name_plural': 'Contracts',
            },
        ),
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('inn', models.CharField(max_length=20, verbose_name='INN')),
                ('type', models.CharField(choices=[('CUSTOMER', 'Customer'), ('SUPPLIER', 'Supplier'), ('AGENT', 'Agent')], max_length=20, verbose_name='Type')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Counterparty',
                'verbose_name_plural': 'Counterparties',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('symbol', models.CharField(blank=True, max_length=5, verbose_name='Symbol')),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('rate', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Rate')),
            ],
            options={
                'verbose_name': 'Exchange Rate',
                'verbose_name_plural': 'Exchange Rates',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('sku', models.CharField(max_length=50, verbose_name='SKU')),
                ('item_type', models.CharField(choices=[('GOODS', 'Good'), ('SERVICE', 'Service')], default='GOODS', max_length=20, verbose_name='Type')),
                ('unit', models.CharField(default='pcs', max_length=20, verbose_name='Unit')),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Purchase Price')),
                ('selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Selling Price')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Address')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Warehouse',
                'verbose_name_plural': 'Warehouses',
            },
        ),
    ]
