# Generated by Django 5.2.6 on 2026-01-25 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directories', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='counterparty',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counterparties', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='contract',
            name='counterparty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='directories.counterparty'),
        ),
        migrations.AddField(
            model_name='contract',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directories.currency'),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directories.currency'),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_rates', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='item',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='tenants.tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='counterparty',
            unique_together={('tenant', 'inn')},
        ),
        migrations.AlterUniqueTogether(
            name='exchangerate',
            unique_together={('tenant', 'currency', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('tenant', 'sku')},
        ),
    ]
