# Generated by Django 5.2.6 on 2026-01-26 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0003_alter_exchangerate_options_exchangerate_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='warehouse_type',
            field=models.CharField(choices=[('PHYSICAL', 'Physical Store/Warehouse'), ('VIRTUAL', 'Virtual/Logical'), ('TRANSIT', 'Goods in Transit')], default='PHYSICAL', max_length=20, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
