# Generated by Django 5.2.6 on 2026-01-27 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0004_warehouse_warehouse_type_alter_warehouse_is_active'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Position')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='directories.counterparty')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Contact Person',
                'verbose_name_plural': 'Contact Persons',
                'unique_together': {('counterparty', 'email')},
            },
        ),
    ]
