# Generated by Django 5.2.6 on 2026-02-05 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0005_contactperson'),
        ('tenants', '0002_permission_rolepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='Code')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='directories.itemcategory')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_categories', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Item Category',
                'verbose_name_plural': 'Item Categories',
                'unique_together': {('tenant', 'name')},
            },
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='directories.itemcategory'),
        ),
        migrations.CreateModel(
            name='ItemPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Package Name')),
                ('coefficient', models.DecimalField(decimal_places=3, default=1, max_digits=10, verbose_name='Coefficient')),
                ('is_default', models.BooleanField(default=False, verbose_name='Is Default')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='directories.item')),
            ],
            options={
                'verbose_name': 'Item Package',
                'verbose_name_plural': 'Item Packages',
            },
        ),
    ]
