# Generated by Django 5.2.6 on 2026-02-06 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0007_bankaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='markup_base_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_currencies', to='directories.currency'),
        ),
        migrations.AddField(
            model_name='currency',
            name='markup_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Percentage added to base rate', max_digits=5, verbose_name='Markup %'),
        ),
        migrations.AddField(
            model_name='currency',
            name='rate_source',
            field=models.CharField(choices=[('MANUAL', 'Manual Input'), ('CBR', 'Download from Internet (CBR/CBU)'), ('MARKUP', 'Markup on Base Currency')], default='MANUAL', max_length=20, verbose_name='Rate Source'),
        ),
    ]
