# Generated by Django 5.2.6 on 2026-02-11 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0010_department_project'),
        ('tenants', '0002_permission_rolepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashFlowItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('activity_type', models.CharField(choices=[('OPERATING', 'Operating Activities'), ('INVESTING', 'Investing Activities'), ('FINANCING', 'Financing Activities')], max_length=20, verbose_name='Activity Type')),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_flow_items', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Cash Flow Item',
                'verbose_name_plural': 'Cash Flow Items',
                'ordering': ['activity_type', 'name'],
                'unique_together': {('tenant', 'name')},
            },
        ),
    ]
