# Generated by Django 5.2.6 on 2026-02-16 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_accountingentry_cash_flow_item'),
        ('directories', '0013_bankoperationtype'),
        ('tenants', '0003_alter_tenant_inn'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='account_type',
            field=models.CharField(choices=[('settlement', 'Settlement'), ('foreign', 'Foreign Currency'), ('deposit', 'Deposit')], default='settlement', max_length=20, verbose_name='Account Type'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='accounting_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bank_accounts', to='accounting.chartofaccounts'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Default For Tenant'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='minimum_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Minimum Balance'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='opening_date',
            field=models.DateField(blank=True, null=True, verbose_name='Opening Date'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='overdraft_allowed',
            field=models.BooleanField(default=False, verbose_name='Overdraft Allowed'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='overdraft_limit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Overdraft Limit'),
        ),
        migrations.CreateModel(
            name='BankExchangeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_format', models.CharField(choices=[('CSV', 'CSV'), ('CLIENT_BANK_1C', '1C ClientBank'), ('ISO20022', 'ISO20022'), ('API', 'Bank API')], default='CSV', max_length=30, verbose_name='Exchange Format')),
                ('bank_program_name', models.CharField(blank=True, max_length=100, verbose_name='Bank Program Name')),
                ('encoding', models.CharField(choices=[('WINDOWS-1251', 'Windows (CP1251)'), ('DOS-866', 'DOS (CP866)'), ('UTF-8', 'UTF-8')], default='UTF-8', max_length=20, verbose_name='Encoding')),
                ('auto_create_counterparties', models.BooleanField(default=True, verbose_name='Auto Create Counterparties')),
                ('new_counterparty_group_name', models.CharField(blank=True, max_length=100, verbose_name='New Counterparty Group')),
                ('auto_detect_bank_fees', models.BooleanField(default=True, verbose_name='Auto Detect Bank Fees')),
                ('auto_post_incoming', models.BooleanField(default=False, verbose_name='Auto Post Incoming')),
                ('auto_post_outgoing', models.BooleanField(default=False, verbose_name='Auto Post Outgoing')),
                ('show_form_before_import', models.BooleanField(default=True, verbose_name='Show Form Before Import')),
                ('export_payment_orders', models.BooleanField(default=True, verbose_name='Export Payment Orders')),
                ('export_payment_claims', models.BooleanField(default=False, verbose_name='Export Payment Claims')),
                ('validate_document_number', models.BooleanField(default=True, verbose_name='Validate Document Number')),
                ('validate_exchange_security', models.BooleanField(default=True, verbose_name='Validate Exchange Security')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_settings', to='directories.bankaccount')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_exchange_settings', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Bank Exchange Settings',
                'verbose_name_plural': 'Bank Exchange Settings',
            },
        ),
    ]
