# Generated by Django 5.2.6 on 2026-02-21 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0014_bankaccount_account_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='counterparty',
            name='extra_fields',
            field=models.JSONField(blank=True, default=dict, verbose_name='Additional Attributes'),
        ),
        migrations.AddField(
            model_name='item',
            name='extra_fields',
            field=models.JSONField(blank=True, default=dict, verbose_name='Additional Attributes'),
        ),
    ]
