# Generated by Django 5.2.6 on 2026-01-25 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesdocument',
            name='rate',
            field=models.DecimalField(decimal_places=6, default=1, help_text='Rate used at time of posting', max_digits=12, verbose_name='Exchange Rate'),
        ),
        migrations.AddField(
            model_name='salesdocument',
            name='total_amount_base',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Calculated as Amount * Rate', max_digits=15, verbose_name='Total Amount (Base Currency)'),
        ),
        migrations.AlterField(
            model_name='salesdocument',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total Amount (Doc Currency)'),
        ),
    ]
