# Generated by Django 5.2.6 on 2026-01-27 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0005_contactperson'),
        ('documents', '0002_salesdocument_rate_salesdocument_total_amount_base_and_more'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='Number')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('cancelled', 'Cancelled')], default='draft', max_length=20, verbose_name='Status')),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('responsible', models.CharField(blank=True, max_length=255, verbose_name='Responsible Person')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventories', to='directories.warehouse')),
            ],
            options={
                'verbose_name': 'Inventory Document',
                'verbose_name_plural': 'Inventory Documents',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InventoryDocumentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_book', models.DecimalField(decimal_places=3, help_text='Quantity according to system (from StockBalance)', max_digits=15, verbose_name='Book Quantity')),
                ('quantity_actual', models.DecimalField(decimal_places=3, help_text='Physically counted quantity', max_digits=15, verbose_name='Actual Quantity')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='documents.inventorydocument')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directories.item')),
            ],
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='Number')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('cancelled', 'Cancelled')], default='draft', max_length=20, verbose_name='Status')),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total Amount')),
                ('is_fully_shipped', models.BooleanField(default=False, help_text='True when all lines are shipped via SalesDocuments')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='directories.contract')),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='directories.counterparty')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directories.currency')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('warehouse', models.ForeignKey(help_text='Warehouse from which goods will be shipped', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='directories.warehouse')),
            ],
            options={
                'verbose_name': 'Sales Order',
                'verbose_name_plural': 'Sales Orders',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalesOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Quantity')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Price')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Amount')),
                ('quantity_shipped', models.DecimalField(decimal_places=3, default=0, help_text='How much has been shipped via SalesDocuments', max_digits=15, verbose_name='Quantity Shipped')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directories.item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='documents.salesorder')),
            ],
        ),
    ]
