# Generated by Django 5.2.6 on 2026-01-29 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('documents', '0003_inventorydocument_inventorydocumentline_salesorder_and_more'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrectionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_object_id', models.PositiveIntegerField()),
                ('number', models.CharField(max_length=50, verbose_name='Correction Number')),
                ('correction_date', models.DateTimeField(help_text='Дата исправления (ТЕКУЩАЯ, не дата оригинала!)', verbose_name='Correction Date')),
                ('correction_reason', models.TextField(help_text='ОБЯЗАТЕЛЬНО: Почему нужно исправление?', verbose_name='Correction Reason')),
                ('correction_type', models.CharField(choices=[('FULL_REVERSAL', 'Полная отмена (Full Reversal)'), ('PARTIAL_CORRECTION', 'Частичное исправление (Partial Correction)'), ('AMOUNT_CORRECTION', 'Исправление суммы (Amount Correction)'), ('VAT_CORRECTION', 'Исправление НДС (VAT Correction)')], max_length=30, verbose_name='Correction Type')),
                ('new_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20, verbose_name='Status')),
                ('posted_at', models.DateTimeField(blank=True, null=True, verbose_name='Posted At')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('new_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='correction_new_documents', to='contenttypes.contenttype')),
                ('original_content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Correction Document',
                'verbose_name_plural': 'Correction Documents',
                'ordering': ['-correction_date'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='documents_c_tenant__55b3fa_idx'), models.Index(fields=['original_content_type', 'original_object_id'], name='documents_c_origina_756114_idx'), models.Index(fields=['correction_date'], name='documents_c_correct_18e5ac_idx')],
            },
        ),
    ]
