# Generated by Django 5.2.6 on 2026-01-29 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_correctiondocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedocument',
            name='rate',
            field=models.DecimalField(decimal_places=6, default=1, help_text='Rate used at time of posting', max_digits=12, verbose_name='Exchange Rate'),
        ),
        migrations.AddField(
            model_name='purchasedocument',
            name='total_amount_base',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Calculated as Amount * Rate', max_digits=15, verbose_name='Total Amount (Base Currency)'),
        ),
        migrations.AddField(
            model_name='purchasedocumentline',
            name='amount_base',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15, verbose_name='Amount (Base)'),
        ),
        migrations.AddField(
            model_name='purchasedocumentline',
            name='price_base',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15, verbose_name='Price (Base)'),
        ),
        migrations.AddField(
            model_name='salesdocumentline',
            name='amount_base',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15, verbose_name='Amount (Base)'),
        ),
        migrations.AddField(
            model_name='salesdocumentline',
            name='price_base',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15, verbose_name='Price (Base)'),
        ),
    ]
