# Generated by Django 5.2.6 on 2026-02-05 00:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0005_contactperson'),
        ('documents', '0006_inventorydocument_created_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesorder',
            options={'ordering': ['-date', '-number'], 'verbose_name': 'Sales Order', 'verbose_name_plural': 'Sales Orders'},
        ),
        migrations.AlterModelOptions(
            name='salesorderline',
            options={'verbose_name': 'Sales Order Line', 'verbose_name_plural': 'Sales Order Lines'},
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='is_fully_shipped',
        ),
        migrations.RenameField(
            model_name='salesorderline',
            old_name='order',
            new_name='document',
        ),
        migrations.RemoveField(
            model_name='salesorderline',
            name='quantity_shipped',
        ),
        migrations.AddField(
            model_name='salesorder',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='Delivery Date'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='order_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Order Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesorder',
            name='rate',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=12, verbose_name='Exchange Rate'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='shipped_document',
            field=models.ForeignKey(blank=True, help_text='Sales Document created from this order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_orders', to='documents.salesdocument'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='total_amount_base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total Amount (Base)'),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='amount_base',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15, verbose_name='Amount (Base)'),
        ),
        migrations.AlterField(
            model_name='salesorderline',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='documents.salesorder'),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='price_base',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15, verbose_name='Price (Base)'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='directories.contract'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='counterparty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='directories.counterparty'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='directories.warehouse'),
        ),
        migrations.AlterField(
            model_name='salesorderline',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Amount'),
        ),
    ]
