# Generated by Django 5.2.6 on 2026-02-05 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0006_itemcategory_item_category_itempackage'),
        ('documents', '0007_alter_salesorder_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesdocumentline',
            name='coefficient',
            field=models.DecimalField(decimal_places=3, default=1, help_text='Snapshot of pack coefficient', max_digits=10, verbose_name='Coefficient'),
        ),
        migrations.AddField(
            model_name='salesdocumentline',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='directories.itempackage'),
        ),
        migrations.AlterField(
            model_name='salesdocumentline',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Quantity (Base)'),
        ),
    ]
