# Generated by Django 5.2.6 on 2026-02-05 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0007_bankaccount'),
        ('documents', '0008_salesdocumentline_coefficient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdocument',
            name='bank_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='directories.bankaccount'),
        ),
        migrations.AddField(
            model_name='paymentdocument',
            name='purpose',
            field=models.TextField(blank=True, help_text='Назначение платежа', verbose_name='Payment Purpose'),
        ),
        migrations.AddField(
            model_name='paymentdocument',
            name='rate',
            field=models.DecimalField(decimal_places=6, default=1, help_text='Rate used at time of posting', max_digits=12, verbose_name='Exchange Rate'),
        ),
    ]
