# Generated by Django 5.2.6 on 2026-02-06 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('directories', '0007_bankaccount'),
        ('documents', '0009_paymentdocument_bank_account_paymentdocument_purpose_and_more'),
        ('tenants', '0002_permission_rolepermission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='Number')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('cancelled', 'Cancelled')], default='draft', max_length=20, verbose_name='Status')),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('statement_date', models.DateField(verbose_name='Statement Date')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Opening Balance')),
                ('closing_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Closing Balance')),
                ('total_receipts', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total Receipts')),
                ('total_payments', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total Payments')),
                ('file', models.FileField(blank=True, null=True, upload_to='bank_statements/%Y/%m/', verbose_name='Statement File')),
                ('lines_count', models.IntegerField(default=0, verbose_name='Lines Count')),
                ('matched_count', models.IntegerField(default=0, verbose_name='Matched Lines')),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='statements', to='directories.bankaccount', verbose_name='Bank Account')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_posted', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Bank Statement',
                'verbose_name_plural': 'Bank Statements',
                'ordering': ['-statement_date', '-number'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BankStatementLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField(verbose_name='Transaction Date')),
                ('debit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Debit Amount')),
                ('credit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Credit Amount')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Balance')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('counterparty_name', models.CharField(blank=True, max_length=255, verbose_name='Counterparty Name')),
                ('matched_document_id', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('unmatched', 'Unmatched'), ('matched', 'Matched'), ('ignored', 'Ignored')], default='unmatched', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('counterparty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_statement_lines', to='directories.counterparty', verbose_name='Counterparty')),
                ('matched_document_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='documents.bankstatement', verbose_name='Statement')),
            ],
            options={
                'verbose_name': 'Bank Statement Line',
                'verbose_name_plural': 'Bank Statement Lines',
                'ordering': ['transaction_date', 'id'],
            },
        ),
    ]
