# Generated by Django 5.2.6 on 2026-02-07 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0008_currency_markup_base_currency_and_more'),
        ('documents', '0010_bankstatement_bankstatementline'),
        ('tenants', '0002_permission_rolepermission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankstatementline',
            options={'verbose_name': 'Bank Statement Line', 'verbose_name_plural': 'Bank Statement Lines'},
        ),
        migrations.CreateModel(
            name='CashOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='Number')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('cancelled', 'Cancelled')], default='draft', max_length=20, verbose_name='Status')),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('order_type', models.CharField(choices=[('incoming', 'Incoming (PKO)'), ('outgoing', 'Outgoing (RKO)')], max_length=20, verbose_name='Order Type')),
                ('counterparty_name', models.CharField(help_text='Person or organization', max_length=255, verbose_name='Counterparty Name')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Amount')),
                ('purpose', models.TextField(help_text='Reason for cash transaction', verbose_name='Purpose')),
                ('basis', models.CharField(blank=True, help_text='Reference document number', max_length=255, verbose_name='Basis Document')),
                ('counterparty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_orders', to='directories.counterparty')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='directories.currency')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_posted', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Cash Order',
                'verbose_name_plural': 'Cash Orders',
                'ordering': ['date', 'id'],
                'abstract': False,
            },
        ),
    ]
