# Generated by Django 5.2.6 on 2026-02-07 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0008_currency_markup_base_currency_and_more'),
        ('documents', '0011_alter_bankstatementline_options_cashorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedocument',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Subtotal'),
        ),
        migrations.AddField(
            model_name='purchasedocument',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Tax Amount'),
        ),
        migrations.AddField(
            model_name='purchasedocumentline',
            name='coefficient',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10, verbose_name='Coefficient'),
        ),
        migrations.AddField(
            model_name='purchasedocumentline',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='directories.itempackage'),
        ),
        migrations.AddField(
            model_name='purchasedocumentline',
            name='total_with_vat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total with VAT'),
        ),
        migrations.AddField(
            model_name='purchasedocumentline',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='VAT Amount'),
        ),
        migrations.AddField(
            model_name='purchasedocumentline',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='VAT Rate'),
        ),
    ]
