# Generated by Django 5.2.6 on 2026-02-07 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_purchasedocument_subtotal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorydocumentline',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15, verbose_name='Amount'),
        ),
        migrations.AddField(
            model_name='inventorydocumentline',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Estimated price for surplus', max_digits=15, verbose_name='Price'),
        ),
    ]
