# Generated by Django 5.2.6 on 2026-02-07 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0009_employee'),
        ('documents', '0014_payrolldocument_payrolldocumentline'),
        ('tenants', '0002_permission_rolepermission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='Number')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('cancelled', 'Cancelled')], default='draft', max_length=20, verbose_name='Status')),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('production_account_code', models.CharField(default='20.01', help_text='Account to accumulate costs (Debit) and release goods (Credit)', max_length=10, verbose_name='Production Account')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('materials_warehouse', models.ForeignKey(blank=True, help_text='Warehouse where materials are taken from. If empty, uses main warehouse.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_inputs', to='directories.warehouse')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_posted', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_outputs', to='directories.warehouse')),
            ],
            options={
                'verbose_name': 'Production Document',
                'verbose_name_plural': 'Production Documents',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductionMaterialLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Quantity')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Cost Price')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Qty * Cost', max_digits=15, verbose_name='Amount')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='documents.productiondocument')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directories.item')),
            ],
            options={
                'verbose_name': 'Consumed Material',
            },
        ),
        migrations.CreateModel(
            name='ProductionProductLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Quantity')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Planned Cost')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Qty * Planned Price', max_digits=15, verbose_name='Amount')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='documents.productiondocument')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directories.item')),
            ],
            options={
                'verbose_name': 'Produced Product',
            },
        ),
    ]
