# Generated by Django 5.2.6 on 2026-02-09 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('directories', '0010_department_project'),
        ('documents', '0016_document_chain'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionmaterialline',
            name='coefficient',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10, verbose_name='Coefficient'),
        ),
        migrations.AddField(
            model_name='productionmaterialline',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='directories.itempackage'),
        ),
        migrations.AddField(
            model_name='productionproductline',
            name='coefficient',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10, verbose_name='Coefficient'),
        ),
        migrations.AddField(
            model_name='productionproductline',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='directories.itempackage'),
        ),
        migrations.AlterField(
            model_name='bankstatement',
            name='base_document_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_based_on', to='contenttypes.contenttype', verbose_name='Base Document Type'),
        ),
        migrations.AlterField(
            model_name='cashorder',
            name='base_document_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_based_on', to='contenttypes.contenttype', verbose_name='Base Document Type'),
        ),
        migrations.AlterField(
            model_name='inventorydocument',
            name='base_document_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_based_on', to='contenttypes.contenttype', verbose_name='Base Document Type'),
        ),
        migrations.AlterField(
            model_name='paymentdocument',
            name='base_document_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_based_on', to='contenttypes.contenttype', verbose_name='Base Document Type'),
        ),
        migrations.AlterField(
            model_name='payrolldocument',
            name='base_document_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_based_on', to='contenttypes.contenttype', verbose_name='Base Document Type'),
        ),
        migrations.AlterField(
            model_name='productiondocument',
            name='base_document_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_based_on', to='contenttypes.contenttype', verbose_name='Base Document Type'),
        ),
        migrations.AlterField(
            model_name='purchasedocument',
            name='base_document_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_based_on', to='contenttypes.contenttype', verbose_name='Base Document Type'),
        ),
        migrations.AlterField(
            model_name='salesdocument',
            name='base_document_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_based_on', to='contenttypes.contenttype', verbose_name='Base Document Type'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='base_document_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_based_on', to='contenttypes.contenttype', verbose_name='Base Document Type'),
        ),
        migrations.AlterField(
            model_name='transferdocument',
            name='base_document_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_based_on', to='contenttypes.contenttype', verbose_name='Base Document Type'),
        ),
    ]
