# Generated by Django 5.2.6 on 2026-02-09 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0010_department_project'),
        ('documents', '0017_productionmaterialline_coefficient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedocument',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='directories.department'),
        ),
        migrations.AddField(
            model_name='purchasedocument',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='directories.project'),
        ),
        migrations.AddField(
            model_name='salesdocument',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='directories.department'),
        ),
        migrations.AddField(
            model_name='salesdocument',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='directories.employee', verbose_name='Manager'),
        ),
        migrations.AddField(
            model_name='salesdocument',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='directories.project'),
        ),
    ]
