# Generated by Django 5.2.6 on 2026-02-10 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0018_purchasedocument_department_purchasedocument_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatement',
            name='version',
            field=models.IntegerField(default=1, editable=False, help_text='Incremented on each save to detect concurrent modifications', verbose_name='Version'),
        ),
        migrations.AddField(
            model_name='cashorder',
            name='version',
            field=models.IntegerField(default=1, editable=False, help_text='Incremented on each save to detect concurrent modifications', verbose_name='Version'),
        ),
        migrations.AddField(
            model_name='inventorydocument',
            name='version',
            field=models.IntegerField(default=1, editable=False, help_text='Incremented on each save to detect concurrent modifications', verbose_name='Version'),
        ),
        migrations.AddField(
            model_name='paymentdocument',
            name='version',
            field=models.IntegerField(default=1, editable=False, help_text='Incremented on each save to detect concurrent modifications', verbose_name='Version'),
        ),
        migrations.AddField(
            model_name='payrolldocument',
            name='version',
            field=models.IntegerField(default=1, editable=False, help_text='Incremented on each save to detect concurrent modifications', verbose_name='Version'),
        ),
        migrations.AddField(
            model_name='productiondocument',
            name='version',
            field=models.IntegerField(default=1, editable=False, help_text='Incremented on each save to detect concurrent modifications', verbose_name='Version'),
        ),
        migrations.AddField(
            model_name='purchasedocument',
            name='version',
            field=models.IntegerField(default=1, editable=False, help_text='Incremented on each save to detect concurrent modifications', verbose_name='Version'),
        ),
        migrations.AddField(
            model_name='salesdocument',
            name='version',
            field=models.IntegerField(default=1, editable=False, help_text='Incremented on each save to detect concurrent modifications', verbose_name='Version'),
        ),
        migrations.AddField(
            model_name='salesdocumentline',
            name='price_source',
            field=models.CharField(choices=[('MANUAL', 'Manual Entry'), ('LAST_SALE', 'Last Sale Price'), ('PRICE_LIST', 'Price List'), ('CONTRACT', 'Contract Price'), ('DEFAULT', 'Default Item Price')], default='MANUAL', help_text="Источник цены - для объяснения 'откуда эта цена?'", max_length=20, verbose_name='Price Source'),
        ),
        migrations.AddField(
            model_name='salesdocumentline',
            name='price_source_date',
            field=models.DateField(blank=True, help_text='Дата последней продажи/прайса (если применимо)', null=True, verbose_name='Price Source Date'),
        ),
        migrations.AddField(
            model_name='salesdocumentline',
            name='rate_source',
            field=models.CharField(choices=[('OFFICIAL', 'Official CBU Rate'), ('MANUAL', 'Manual Entry'), ('CONTRACT', 'Contract Rate')], default='OFFICIAL', help_text='Источник курса валюты', max_length=20, verbose_name='Rate Source'),
        ),
        migrations.AddField(
            model_name='salesdocumentline',
            name='rate_source_date',
            field=models.DateField(blank=True, help_text='Дата официального курса', null=True, verbose_name='Rate Source Date'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='version',
            field=models.IntegerField(default=1, editable=False, help_text='Incremented on each save to detect concurrent modifications', verbose_name='Version'),
        ),
        migrations.AddField(
            model_name='transferdocument',
            name='version',
            field=models.IntegerField(default=1, editable=False, help_text='Incremented on each save to detect concurrent modifications', verbose_name='Version'),
        ),
        migrations.AlterField(
            model_name='bankstatement',
            name='number',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='cashorder',
            name='number',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='inventorydocument',
            name='number',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='paymentdocument',
            name='number',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='payrolldocument',
            name='number',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='productiondocument',
            name='number',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='purchasedocument',
            name='number',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='salesdocument',
            name='number',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='number',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='transferdocument',
            name='number',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Number'),
        ),
    ]
