# Generated by Django 5.2.6 on 2026-02-11 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('directories', '0011_cashflowitem'),
        ('documents', '0019_add_version_optimistic_locking'),
        ('tenants', '0002_permission_rolepermission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpeningBalanceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Number')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('cancelled', 'Cancelled')], default='draft', max_length=20, verbose_name='Status')),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.IntegerField(default=1, editable=False, help_text='Incremented on each save to detect concurrent modifications', verbose_name='Version')),
                ('base_document_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Base Document ID')),
                ('operation_type', models.CharField(choices=[('stock', 'Stock Balances'), ('settlement', 'Settlement Balances'), ('account', 'Account Balances')], max_length=20, verbose_name='Operation Type')),
                ('base_document_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_based_on', to='contenttypes.contenttype', verbose_name='Base Document Type')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_posted', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='directories.warehouse')),
            ],
            options={
                'verbose_name': 'Opening Balance Document',
                'verbose_name_plural': 'Opening Balance Documents',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OpeningBalanceSettlementLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('receivable', 'Receivable (Debit)'), ('payable', 'Payable (Credit)')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Amount')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='directories.contract')),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directories.counterparty')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlement_lines', to='documents.openingbalancedocument')),
            ],
        ),
        migrations.CreateModel(
            name='OpeningBalanceStockLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Quantity')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Cost (Base)')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Amount')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_lines', to='documents.openingbalancedocument')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directories.item')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='directories.warehouse')),
            ],
        ),
    ]
