# Generated by Django 5.2.6 on 2026-02-11 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0020_openingbalancedocument_openingbalancesettlementline_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesdocument',
            name='rate',
        ),
        migrations.AddField(
            model_name='salesdocument',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Subtotal'),
        ),
        migrations.AddField(
            model_name='salesdocument',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Tax Amount'),
        ),
        migrations.AddField(
            model_name='salesdocumentline',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Discount %'),
        ),
        migrations.AddField(
            model_name='salesdocumentline',
            name='total_with_vat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total with VAT'),
        ),
        migrations.AddField(
            model_name='salesdocumentline',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='VAT Amount'),
        ),
        migrations.AddField(
            model_name='salesdocumentline',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='VAT Rate'),
        ),
        migrations.AlterField(
            model_name='salesdocument',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total Amount'),
        ),
    ]
