# Generated by Codex on 2026-02-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0021_remove_salesdocument_rate_salesdocument_subtotal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesdocument',
            name='rate',
            field=models.DecimalField(
                decimal_places=6,
                default=1,
                help_text='Currency units per 1 USD',
                max_digits=12,
                verbose_name='Exchange Rate',
            ),
        ),
    ]

