# Generated by Django 5.2.6 on 2026-02-16 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_accountingentry_cash_flow_item'),
        ('directories', '0014_bankaccount_account_type_and_more'),
        ('documents', '0026_bankstatement_reconciliation_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatement',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bank_statements', to='directories.currency'),
        ),
        migrations.AddField(
            model_name='bankstatementline',
            name='bank_document_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bank Document Number'),
        ),
        migrations.AddField(
            model_name='bankstatementline',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_statement_lines', to='directories.contract', verbose_name='Contract'),
        ),
        migrations.AddField(
            model_name='bankstatementline',
            name='payment_purpose',
            field=models.TextField(blank=True, verbose_name='Payment Purpose'),
        ),
        migrations.AddField(
            model_name='cashorder',
            name='cash_desk',
            field=models.CharField(default='Main Cash Desk', max_length=100, verbose_name='Cash Desk'),
        ),
        migrations.AddField(
            model_name='cashorder',
            name='cash_flow_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_orders', to='directories.cashflowitem'),
        ),
        migrations.AddField(
            model_name='cashorder',
            name='credit_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_orders_credit', to='accounting.chartofaccounts'),
        ),
        migrations.AddField(
            model_name='cashorder',
            name='debit_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_orders_debit', to='accounting.chartofaccounts'),
        ),
        migrations.AddField(
            model_name='paymentdocument',
            name='basis',
            field=models.CharField(blank=True, max_length=255, verbose_name='Basis'),
        ),
        migrations.AddField(
            model_name='paymentdocument',
            name='cash_flow_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_documents', to='directories.cashflowitem'),
        ),
        migrations.AddField(
            model_name='paymentdocument',
            name='credit_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_documents_credit', to='accounting.chartofaccounts'),
        ),
        migrations.AddField(
            model_name='paymentdocument',
            name='debit_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_documents_debit', to='accounting.chartofaccounts'),
        ),
        migrations.AddField(
            model_name='paymentdocument',
            name='payment_kind',
            field=models.CharField(choices=[('supplier', 'Supplier'), ('tax', 'Tax'), ('salary', 'Salary'), ('other', 'Other')], default='other', max_length=20, verbose_name='Payment Kind'),
        ),
        migrations.AddField(
            model_name='paymentdocument',
            name='payment_priority',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='Payment Priority'),
        ),
        migrations.AddField(
            model_name='paymentdocument',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='VAT Amount'),
        ),
        migrations.AlterField(
            model_name='bankstatementline',
            name='operation_type',
            field=models.CharField(choices=[('CUSTOMER_PAYMENT', 'Customer Payment'), ('SUPPLIER_PAYMENT', 'Supplier Payment'), ('TAX_PAYMENT', 'Tax Payment'), ('BANK_FEE', 'Bank Fee'), ('TRANSFER_INTERNAL', 'Internal Transfer'), ('SALARY_PAYMENT', 'Salary Payment'), ('ACCOUNTABLE', 'Accountable Person'), ('LOAN_RETURN', 'Loan Return'), ('OTHER', 'Other')], default='OTHER', max_length=30, verbose_name='Operation Type'),
        ),
    ]
