# Generated by Django 5.2.6 on 2026-02-17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0010_department_project'),
        ('documents', '0027_remove_salesdocument_rate_bankstatement_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorderline',
            name='coefficient',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10, verbose_name='Coefficient'),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='directories.itempackage'),
        ),
    ]
