# Generated by Django 5.2.6 on 2026-02-20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0014_bankaccount_account_type_and_more'),
        ('documents', '0028_salesorderline_packaging_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpeningBalanceAccountLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Amount')),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directories.bankaccount')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_lines', to='documents.openingbalancedocument')),
            ],
        ),
    ]
