# Generated by Django 5.2.6 on 2026-02-20 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0029_openingbalanceaccountline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesdocument',
            name='rate',
        ),
        migrations.AlterField(
            model_name='paymentdocument',
            name='purpose',
            field=models.TextField(blank=True, help_text='РќР°Р·РЅР°С‡РµРЅРёРµ РїР»Р°С‚РµР¶Р°', verbose_name='Payment Purpose'),
        ),
        migrations.AlterField(
            model_name='salesdocumentline',
            name='price_source',
            field=models.CharField(choices=[('MANUAL', 'Manual Entry'), ('LAST_SALE', 'Last Sale Price'), ('PRICE_LIST', 'Price List'), ('CONTRACT', 'Contract Price'), ('DEFAULT', 'Default Item Price')], default='MANUAL', help_text="Р\x98СЃС‚РѕС‡РЅРёРє С†РµРЅС‹ - РґР»СЏ РѕР±СЉСЏСЃРЅРµРЅРёСЏ 'РѕС‚РєСѓРґР° СЌС‚Р° С†РµРЅР°?'", max_length=20, verbose_name='Price Source'),
        ),
        migrations.AlterField(
            model_name='salesdocumentline',
            name='price_source_date',
            field=models.DateField(blank=True, help_text='Р”Р°С‚Р° РїРѕСЃР»РµРґРЅРµР№ РїСЂРѕРґР°Р¶Рё/РїСЂР°Р№СЃР° (РµСЃР»Рё РїСЂРёРјРµРЅРёРјРѕ)', null=True, verbose_name='Price Source Date'),
        ),
        migrations.AlterField(
            model_name='salesdocumentline',
            name='rate_source',
            field=models.CharField(choices=[('OFFICIAL', 'Official CBU Rate'), ('MANUAL', 'Manual Entry'), ('CONTRACT', 'Contract Rate')], default='OFFICIAL', help_text='Р\x98СЃС‚РѕС‡РЅРёРє РєСѓСЂСЃР° РІР°Р»СЋС‚С‹', max_length=20, verbose_name='Rate Source'),
        ),
        migrations.AlterField(
            model_name='salesdocumentline',
            name='rate_source_date',
            field=models.DateField(blank=True, help_text='Р”Р°С‚Р° РѕС„РёС†РёР°Р»СЊРЅРѕРіРѕ РєСѓСЂСЃР°', null=True, verbose_name='Rate Source Date'),
        ),
    ]
