# Generated by Django 5.2.6 on 2026-02-07 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0007_accountingpolicy_accountingpolicyhistory'),
        ('directories', '0008_currency_markup_base_currency_and_more'),
        ('tenants', '0002_permission_rolepermission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedAssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Code')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('default_useful_life_months', models.IntegerField(default=60, help_text='5 years default', verbose_name='Default Useful Life (Months)')),
                ('default_depreciation_method', models.CharField(choices=[('LINEAR', 'Linear (Straight-line)'), ('DECLINING', 'Declining Balance')], default='LINEAR', max_length=20, verbose_name='Default Depreciation Method')),
                ('asset_account', models.ForeignKey(blank=True, help_text='Default account 01 (Fixed Assets)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fa_categories_asset', to='accounting.chartofaccounts')),
                ('depreciation_account', models.ForeignKey(blank=True, help_text='Default account 02 (Accumulated Depreciation)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fa_categories_depreciation', to='accounting.chartofaccounts')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='fixed_assets.fixedassetcategory')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fa_categories', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Fixed Asset Category',
                'verbose_name_plural': 'Fixed Asset Categories',
                'ordering': ['code'],
                'unique_together': {('tenant', 'code')},
            },
        ),
        migrations.CreateModel(
            name='FixedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_number', models.CharField(help_text='Unique asset ID', max_length=50, verbose_name='Inventory Number')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('initial_cost', models.DecimalField(decimal_places=2, help_text='Original purchase price', max_digits=15, verbose_name='Initial Cost')),
                ('residual_value', models.DecimalField(decimal_places=2, default=0, help_text='Salvage value', max_digits=15, verbose_name='Residual Value')),
                ('accumulated_depreciation', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15, verbose_name='Accumulated Depreciation')),
                ('depreciation_method', models.CharField(choices=[('LINEAR', 'Linear'), ('DECLINING', 'Declining Balance')], default='LINEAR', max_length=20, verbose_name='Depreciation Method')),
                ('useful_life_months', models.IntegerField(default=60, verbose_name='Useful Life (Months)')),
                ('depreciation_rate', models.DecimalField(blank=True, decimal_places=2, help_text='For declining balance method', max_digits=5, null=True, verbose_name='Depreciation Rate (%)')),
                ('acquisition_date', models.DateField(verbose_name='Acquisition Date')),
                ('commissioning_date', models.DateField(help_text='Date when depreciation starts', verbose_name='Commissioning Date')),
                ('disposal_date', models.DateField(blank=True, null=True, verbose_name='Disposal Date')),
                ('location', models.CharField(blank=True, help_text='Department or physical location', max_length=200, verbose_name='Location')),
                ('status', models.CharField(choices=[('IN_USE', 'In Use'), ('MOTHBALLED', 'Mothballed'), ('DISPOSED', 'Disposed')], default='IN_USE', max_length=20, verbose_name='Status')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='Serial Number')),
                ('manufacturer', models.CharField(blank=True, max_length=200, verbose_name='Manufacturer')),
                ('responsible_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responsible_for_assets', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixed_assets', to='tenants.tenant')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='fixed_assets.fixedassetcategory')),
            ],
            options={
                'verbose_name': 'Fixed Asset',
                'verbose_name_plural': 'Fixed Assets',
                'ordering': ['inventory_number'],
                'unique_together': {('tenant', 'inventory_number')},
            },
        ),
        migrations.CreateModel(
            name='FAReceiptDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='Number')),
                ('date', models.DateField(verbose_name='Date')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted')], default='DRAFT', max_length=20, verbose_name='Status')),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_fa_receipts', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fa_receipts', to='directories.counterparty')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fa_receipts', to='tenants.tenant')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipt_documents', to='fixed_assets.fixedasset')),
            ],
            options={
                'verbose_name': 'FA Receipt Document',
                'verbose_name_plural': 'FA Receipt Documents',
                'ordering': ['-date', '-number'],
                'unique_together': {('tenant', 'number')},
            },
        ),
        migrations.CreateModel(
            name='FADisposalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='Number')),
                ('date', models.DateField(verbose_name='Date')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted')], default='DRAFT', max_length=20, verbose_name='Status')),
                ('reason', models.CharField(choices=[('SALE', 'Sale'), ('SCRAP', 'Scrapped'), ('DONATION', 'Donated'), ('LOSS', 'Lost/Stolen')], max_length=20, verbose_name='Disposal Reason')),
                ('sale_amount', models.DecimalField(blank=True, decimal_places=2, help_text='If sold', max_digits=15, null=True, verbose_name='Sale Amount')),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_fa_disposals', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fa_disposals', to='tenants.tenant')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disposal_documents', to='fixed_assets.fixedasset')),
            ],
            options={
                'verbose_name': 'FA Disposal Document',
                'verbose_name_plural': 'FA Disposal Documents',
                'ordering': ['-date', '-number'],
                'unique_together': {('tenant', 'number')},
            },
        ),
        migrations.CreateModel(
            name='FAAcceptanceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='Number')),
                ('date', models.DateField(verbose_name='Date')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted')], default='DRAFT', max_length=20, verbose_name='Status')),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_fa_acceptances', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fa_acceptances', to='tenants.tenant')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acceptance_documents', to='fixed_assets.fixedasset')),
            ],
            options={
                'verbose_name': 'FA Acceptance Document',
                'verbose_name_plural': 'FA Acceptance Documents',
                'ordering': ['-date', '-number'],
                'unique_together': {('tenant', 'number')},
            },
        ),
        migrations.CreateModel(
            name='DepreciationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(help_text='First day of month', verbose_name='Period')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Depreciation Amount')),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('accounting_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.accountingentry')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depreciation_schedules', to='tenants.tenant')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depreciation_schedule', to='fixed_assets.fixedasset')),
            ],
            options={
                'verbose_name': 'Depreciation Schedule',
                'verbose_name_plural': 'Depreciation Schedules',
                'ordering': ['-period'],
                'unique_together': {('tenant', 'asset', 'period')},
            },
        ),
    ]
