# Generated by Django 5.2.6 on 2026-02-07 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_accountingpolicy_accountingpolicyhistory'),
        ('directories', '0008_currency_markup_base_currency_and_more'),
        ('fixed_assets', '0001_initial'),
        ('tenants', '0002_permission_rolepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntangibleAssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Code')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('default_useful_life_months', models.IntegerField(default=60, verbose_name='Default Useful Life (Months)')),
                ('amortization_account', models.ForeignKey(blank=True, help_text='Default account 05 (Amortization of Intangible Assets)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ia_categories_amortization', to='accounting.chartofaccounts')),
                ('asset_account', models.ForeignKey(blank=True, help_text='Default account 04 (Intangible Assets)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ia_categories_asset', to='accounting.chartofaccounts')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='fixed_assets.intangibleassetcategory')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ia_categories', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Intangible Asset Category',
                'verbose_name_plural': 'Intangible Asset Categories',
                'ordering': ['code'],
                'unique_together': {('tenant', 'code')},
            },
        ),
        migrations.CreateModel(
            name='IntangibleAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_number', models.CharField(help_text='Unique NMA ID', max_length=50, verbose_name='Inventory Number')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('initial_cost', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Initial Cost')),
                ('accumulated_amortization', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15, verbose_name='Accumulated Amortization')),
                ('useful_life_months', models.IntegerField(default=60, verbose_name='Useful Life (Months)')),
                ('acquisition_date', models.DateField(verbose_name='Acquisition Date')),
                ('commissioning_date', models.DateField(verbose_name='Commissioning Date')),
                ('write_off_date', models.DateField(blank=True, null=True, verbose_name='Write-off Date')),
                ('status', models.CharField(choices=[('IN_USE', 'In Use'), ('WRITTEN_OFF', 'Written Off')], default='IN_USE', max_length=20, verbose_name='Status')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intangible_assets', to='tenants.tenant')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='fixed_assets.intangibleassetcategory')),
            ],
            options={
                'verbose_name': 'Intangible Asset',
                'verbose_name_plural': 'Intangible Assets',
                'ordering': ['inventory_number'],
                'unique_together': {('tenant', 'inventory_number')},
            },
        ),
        migrations.CreateModel(
            name='IAReceiptDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='Number')),
                ('date', models.DateField(verbose_name='Date')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted')], default='DRAFT', max_length=20, verbose_name='Status')),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ia_receipts', to='directories.counterparty')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ia_receipts', to='tenants.tenant')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipt_documents', to='fixed_assets.intangibleasset')),
            ],
            options={
                'ordering': ['-date', '-number'],
                'unique_together': {('tenant', 'number')},
            },
        ),
        migrations.CreateModel(
            name='IADisposalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='Number')),
                ('date', models.DateField(verbose_name='Date')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted')], default='DRAFT', max_length=20, verbose_name='Status')),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ia_disposals', to='tenants.tenant')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disposal_documents', to='fixed_assets.intangibleasset')),
            ],
            options={
                'ordering': ['-date', '-number'],
                'unique_together': {('tenant', 'number')},
            },
        ),
        migrations.CreateModel(
            name='IAAcceptanceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='Number')),
                ('date', models.DateField(verbose_name='Date')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted')], default='DRAFT', max_length=20, verbose_name='Status')),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ia_acceptances', to='tenants.tenant')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acceptance_documents', to='fixed_assets.intangibleasset')),
            ],
            options={
                'ordering': ['-date', '-number'],
                'unique_together': {('tenant', 'number')},
            },
        ),
        migrations.CreateModel(
            name='AmortizationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(verbose_name='Period')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Amortization Amount')),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('accounting_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.accountingentry')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amortization_schedules', to='tenants.tenant')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amortization_schedule', to='fixed_assets.intangibleasset')),
            ],
            options={
                'verbose_name': 'Amortization Schedule',
                'verbose_name_plural': 'Amortization Schedules',
                'ordering': ['-period'],
                'unique_together': {('tenant', 'asset', 'period')},
            },
        ),
    ]
