# Generated by Django 5.2.6 on 2026-01-25 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('directories', '0002_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Quantity')),
                ('type', models.CharField(choices=[('IN', 'Income'), ('OUT', 'Outcome'), ('ADJUSTMENT', 'Adjustment')], max_length=15, verbose_name='Type')),
                ('object_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directories.item')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directories.warehouse')),
            ],
            options={
                'verbose_name': 'Stock Movement',
                'verbose_name_plural': 'Stock Movements',
            },
        ),
        migrations.CreateModel(
            name='CounterpartyStockBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Quantity')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Amount')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directories.counterparty')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directories.item')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Counterparty Stock Balance',
                'verbose_name_plural': 'Counterparty Stock Balances',
                'unique_together': {('tenant', 'counterparty', 'item')},
            },
        ),
        migrations.CreateModel(
            name='SettlementsBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Balance')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directories.contract')),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directories.counterparty')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directories.currency')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Settlements Balance',
                'verbose_name_plural': 'Settlements Balances',
                'unique_together': {('tenant', 'counterparty', 'contract', 'currency')},
            },
        ),
        migrations.CreateModel(
            name='StockBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Quantity')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Amount')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directories.item')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directories.warehouse')),
            ],
            options={
                'verbose_name': 'Stock Balance',
                'verbose_name_plural': 'Stock Balances',
                'unique_together': {('tenant', 'warehouse', 'item')},
            },
        ),
    ]
