# Generated by Django 5.2.6 on 2026-01-25 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('directories', '0003_alter_exchangerate_options_exchangerate_created_at_and_more'),
        ('registers', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockbalance',
            options={'verbose_name': 'Stock Balance (Cache)', 'verbose_name_plural': 'Stock Balances (Cache)'},
        ),
        migrations.AlterField(
            model_name='stockbalance',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='stockbalance',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directories.item'),
        ),
        migrations.AlterField(
            model_name='stockbalance',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='stockbalance',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directories.warehouse'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directories.item'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='quantity',
            field=models.DecimalField(decimal_places=3, help_text='Always positive value, Type determines sign', max_digits=15),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='type',
            field=models.CharField(choices=[('IN', 'Incoming (+)'), ('OUT', 'Outgoing (-)')], max_length=10),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directories.warehouse'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['tenant', 'warehouse', 'item'], name='registers_s_tenant__dc1739_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['date'], name='registers_s_date_84a150_idx'),
        ),
    ]
