# Generated by Django 5.2.6 on 2026-01-27 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('directories', '0004_warehouse_warehouse_type_alter_warehouse_is_active'),
        ('registers', '0002_alter_stockbalance_options_alter_stockbalance_amount_and_more'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incoming_document_id', models.PositiveIntegerField()),
                ('incoming_date', models.DateTimeField(verbose_name='Batch Date')),
                ('qty_initial', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Initial Quantity')),
                ('qty_remaining', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Remaining Quantity')),
                ('unit_cost', models.DecimalField(decimal_places=4, help_text='Cost per single unit in base currency', max_digits=15, verbose_name='Unit Cost')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incoming_document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directories.item')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directories.warehouse')),
            ],
            options={
                'verbose_name': 'Stock Batch / Lot',
                'verbose_name_plural': 'Stock Batches / Lots',
                'ordering': ['incoming_date'],
            },
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='Which batch is consumed/created. NULL for movements without batch tracking.', null=True, on_delete=django.db.models.deletion.PROTECT, to='registers.stockbatch'),
        ),
        migrations.CreateModel(
            name='StockReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Reserved Quantity')),
                ('document_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directories.item')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directories.warehouse')),
            ],
            options={
                'verbose_name': 'Stock Reservation',
                'verbose_name_plural': 'Stock Reservations',
            },
        ),
        migrations.AddIndex(
            model_name='stockbatch',
            index=models.Index(fields=['tenant', 'item', 'warehouse', 'incoming_date'], name='registers_s_tenant__9ca509_idx'),
        ),
        migrations.AddIndex(
            model_name='stockreservation',
            index=models.Index(fields=['tenant', 'item', 'warehouse'], name='registers_s_tenant__3df683_idx'),
        ),
    ]
