# Generated by Django 5.2.6 on 2026-01-27 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('directories', '0005_contactperson'),
        ('registers', '0003_stockbatch_stockmovement_batch_stockreservation_and_more'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_valuation_method', models.CharField(choices=[('FIFO', 'First In First Out (FIFO)'), ('AVG', 'Weighted Average'), ('LIFO', 'Last In First Out (LIFO)')], default='FIFO', help_text='Метод оценки товаров при списании', max_length=10, verbose_name='Stock Valuation Method')),
                ('effective_from', models.DateField(verbose_name='Effective From')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accounting_policy', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Accounting Policy',
                'verbose_name_plural': 'Accounting Policies',
            },
        ),
        migrations.CreateModel(
            name='GoodsInTransit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Quantity')),
                ('shipped_date', models.DateTimeField(verbose_name='Shipped Date')),
                ('expected_date', models.DateField(verbose_name='Expected Arrival')),
                ('actual_arrival_date', models.DateTimeField(blank=True, null=True, verbose_name='Actual Arrival')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SHIPPED', 'Shipped by Supplier'), ('IN_TRANSIT', 'In Transit'), ('RECEIVED', 'Received'), ('LOST', 'Lost/Damaged')], default='SHIPPED', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('destination_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transit', to='directories.warehouse')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directories.item')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_in_transit', to='directories.counterparty')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Goods in Transit',
                'verbose_name_plural': 'Goods in Transit',
                'indexes': [models.Index(fields=['tenant', 'status', 'expected_date'], name='registers_g_tenant__d49a1a_idx'), models.Index(fields=['supplier', 'status'], name='registers_g_supplie_a1e38f_idx')],
            },
        ),
    ]
