# Generated by Django 5.2.6 on 2026-01-27 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0004_accountingpolicy_goodsintransit'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsintransit',
            name='carrier',
            field=models.CharField(blank=True, help_text='e.g., DHL, FedEx, СДЭК, Почта России', max_length=100, verbose_name='Carrier'),
        ),
        migrations.AddField(
            model_name='goodsintransit',
            name='risk_status',
            field=models.CharField(choices=[('ON_TIME', 'On Time (Вовремя)'), ('DELAYED', 'Delayed (Задержка)'), ('CRITICAL', 'Critical (Критично)'), ('UNKNOWN', 'Unknown (Неизвестно)')], default='UNKNOWN', help_text='Автоматически рассчитывается по срокам', max_length=20, verbose_name='Risk Status'),
        ),
        migrations.AddField(
            model_name='goodsintransit',
            name='tracking_number',
            field=models.CharField(blank=True, help_text='Номер отслеживания', max_length=100, verbose_name='Tracking Number'),
        ),
        migrations.CreateModel(
            name='AccountingPolicyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valuation_method', models.CharField(choices=[('FIFO', 'First In First Out (FIFO)'), ('AVG', 'Weighted Average'), ('LIFO', 'Last In First Out (LIFO)')], max_length=10, verbose_name='Valuation Method')),
                ('effective_from', models.DateField(verbose_name='Effective From')),
                ('effective_to', models.DateField(blank=True, help_text='NULL = still active', null=True, verbose_name='Effective To')),
                ('changed_by', models.CharField(blank=True, max_length=255, verbose_name='Changed By')),
                ('change_reason', models.TextField(blank=True, verbose_name='Reason for Change')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_history', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Accounting Policy History',
                'verbose_name_plural': 'Accounting Policy History',
                'ordering': ['-effective_from'],
                'indexes': [models.Index(fields=['tenant', 'effective_from'], name='registers_a_tenant__10e9dc_idx')],
            },
        ),
    ]
