# Generated by Django 5.2.6 on 2026-01-27 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('directories', '0005_contactperson'),
        ('registers', '0005_goodsintransit_carrier_goodsintransit_risk_status_and_more'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='is_reversal',
            field=models.BooleanField(default=False, help_text='Сторнирующее движение (отмена предыдущего)', verbose_name='Is Reversal'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='reversed_at',
            field=models.DateTimeField(blank=True, help_text='Когда было сторнировано', null=True, verbose_name='Reversed At'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='reversed_movement',
            field=models.ForeignKey(blank=True, help_text='Ссылка на отменяемое движение', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversals', to='registers.stockmovement'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['is_reversal', 'reversed_movement'], name='registers_s_is_reve_1f951e_idx'),
        ),
    ]
