# Generated by Django 5.2.6 on 2026-01-29 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0006_stockmovement_is_reversal_stockmovement_reversed_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountingpolicyhistory',
            name='tenant',
        ),
        migrations.DeleteModel(
            name='AccountingPolicy',
        ),
        migrations.DeleteModel(
            name='AccountingPolicyHistory',
        ),
    ]
