# Generated by Django 5.2.6 on 2026-02-05 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('directories', '0007_bankaccount'),
        ('registers', '0007_remove_accountingpolicyhistory_tenant_and_more'),
        ('tenants', '0002_permission_rolepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettlementMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, help_text='Negative for Payments, Positive for Accruals (usually)', max_digits=15, verbose_name='Amount')),
                ('object_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directories.contract')),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directories.counterparty')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directories.currency')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Settlement Movement',
                'verbose_name_plural': 'Settlement Movements',
                'indexes': [models.Index(fields=['tenant', 'counterparty', 'contract'], name='registers_s_tenant__333d49_idx'), models.Index(fields=['date'], name='registers_s_date_6f9e3f_idx')],
            },
        ),
    ]
