# Generated by Django 5.2.6 on 2026-02-21 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('directories', '0015_counterparty_extra_fields_item_extra_fields'),
        ('registers', '0008_settlementmovement'),
        ('tenants', '0003_alter_tenant_inn'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Дата установки цены', verbose_name='Date')),
                ('price_type', models.CharField(choices=[('PURCHASE', 'Purchase Price'), ('SELLING', 'Selling Price'), ('WHOLESALE', 'Wholesale Price')], default='SELLING', max_length=20, verbose_name='Price Type')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Price')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directories.currency')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='directories.item')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Item Price',
                'verbose_name_plural': 'Item Prices',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['tenant', 'item', 'date'], name='registers_i_tenant__997b6a_idx')],
                'unique_together': {('tenant', 'item', 'price_type', 'date')},
            },
        ),
    ]
