# Generated by Django 5.2.6 on 2026-01-27 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('directories', '0005_contactperson'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartOfAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g., 41.01, 60, 62', max_length=20, verbose_name='Account Code')),
                ('name', models.CharField(help_text='e.g., Товары на складах', max_length=255, verbose_name='Account Name')),
                ('account_type', models.CharField(choices=[('ASSET', 'Asset (Актив)'), ('LIABILITY', 'Liability (Пассив)'), ('EQUITY', 'Equity (Капитал)'), ('REVENUE', 'Revenue (Доход)'), ('EXPENSE', 'Expense (Расход)')], max_length=20, verbose_name='Account Type')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='accounting.chartofaccounts')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chart_of_accounts', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Chart of Accounts',
                'verbose_name_plural': 'Chart of Accounts',
                'ordering': ['code'],
                'unique_together': {('tenant', 'code')},
            },
        ),
        migrations.CreateModel(
            name='AccountingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('period', models.DateField(help_text='YYYY-MM-01 for monthly closing', verbose_name='Accounting Period')),
                ('object_id', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Amount')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directories.currency')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('credit_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_entries', to='accounting.chartofaccounts', verbose_name='Credit Account')),
                ('debit_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debit_entries', to='accounting.chartofaccounts', verbose_name='Debit Account')),
            ],
            options={
                'verbose_name': 'Accounting Entry',
                'verbose_name_plural': 'Accounting Entries',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['tenant', 'period'], name='accounting__tenant__5b0068_idx'), models.Index(fields=['debit_account', 'period'], name='accounting__debit_a_e57573_idx'), models.Index(fields=['credit_account', 'period'], name='accounting__credit__b42002_idx'), models.Index(fields=['date'], name='accounting__date_549536_idx')],
            },
        ),
        migrations.CreateModel(
            name='TrialBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(verbose_name='Period')),
                ('opening_debit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Opening Debit')),
                ('opening_credit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Opening Credit')),
                ('turnover_debit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Turnover Debit')),
                ('turnover_credit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Turnover Credit')),
                ('closing_debit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Closing Debit')),
                ('closing_credit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Closing Credit')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.chartofaccounts')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Trial Balance',
                'verbose_name_plural': 'Trial Balances',
                'ordering': ['period', 'account__code'],
                'unique_together': {('tenant', 'account', 'period')},
            },
        ),
    ]
