# Generated by Django 5.2.6 on 2026-01-27 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('directories', '0005_contactperson'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VATRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="e.g., '20%', '10%', '0%'", max_length=20, verbose_name='Code')),
                ('rate', models.DecimalField(decimal_places=2, help_text='e.g., 20.00 for 20%', max_digits=5, verbose_name='Rate')),
                ('is_default', models.BooleanField(default=False, verbose_name='Default Rate')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vat_rates', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'VAT Rate',
                'verbose_name_plural': 'VAT Rates',
                'ordering': ['-rate'],
                'unique_together': {('tenant', 'code')},
            },
        ),
        migrations.CreateModel(
            name='VATTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('period', models.DateField(help_text='YYYY-MM-01', verbose_name='Tax Period')),
                ('object_id', models.PositiveIntegerField()),
                ('vat_type', models.CharField(choices=[('INPUT', 'VAT Input (к вычету)'), ('OUTPUT', 'VAT Output (к уплате)')], max_length=10, verbose_name='VAT Type')),
                ('base_amount', models.DecimalField(decimal_places=2, help_text='Amount without VAT', max_digits=15, verbose_name='Base Amount')),
                ('vat_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='VAT Amount')),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Base + VAT', max_digits=15, verbose_name='Total Amount')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directories.currency')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('vat_rate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.vatrate')),
            ],
            options={
                'verbose_name': 'VAT Transaction',
                'verbose_name_plural': 'VAT Transactions',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['tenant', 'period', 'vat_type'], name='accounting__tenant__d19705_idx'), models.Index(fields=['date'], name='accounting__date_bc47d0_idx')],
            },
        ),
    ]
