# Generated by Django 5.2.6 on 2026-01-27 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_vatrate_vattransaction'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodClosing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(help_text='YYYY-MM-01 - первое число месяца', verbose_name='Period')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSING', 'Closing in Progress'), ('CLOSED', 'Closed'), ('REOPENED', 'Reopened for adjustments')], default='OPEN', max_length=20, verbose_name='Status')),
                ('operational_closed', models.BooleanField(default=False, help_text='Закрыт оперативный учёт (склад, продажи)', verbose_name='Operational Closed')),
                ('accounting_closed', models.BooleanField(default=False, help_text='Закрыт бухгалтерский учёт (проводки, НДС)', verbose_name='Accounting Closed')),
                ('allow_operational_after_close', models.BooleanField(default=True, help_text='Разрешить оперативные движения после закрытия бухучёта', verbose_name='Allow Operational After Close')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Closed At')),
                ('profit_loss', models.DecimalField(decimal_places=2, default=0, help_text='Прибыль/убыток за период', max_digits=15, verbose_name='П/У (Profit/Loss)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_periods', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_closings', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Period Closing',
                'verbose_name_plural': 'Period Closings',
                'ordering': ['-period'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='accounting__tenant__5346c4_idx'), models.Index(fields=['period', 'status'], name='accounting__period_b9368e_idx')],
                'unique_together': {('tenant', 'period')},
            },
        ),
    ]
