# Generated by Django 5.2.6 on 2026-01-27 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_periodclosing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingentry',
            name='accounting_period',
            field=models.ForeignKey(blank=True, help_text='Явная связь с периодом - для детерминированных отчётов', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='accounting.periodclosing'),
        ),
        migrations.CreateModel(
            name='PeriodClosingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CLOSE', 'Close Period'), ('REOPEN', 'Reopen Period'), ('FORCE_REOPEN', 'Force Reopen (SuperAdmin)')], max_length=20, verbose_name='Action')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('reason', models.TextField(help_text='Обязательная причина для REOPEN', verbose_name='Reason')),
                ('user_role', models.CharField(blank=True, help_text='e.g., Chief Accountant, SuperAdmin', max_length=100, verbose_name='User Role')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('period_closing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='accounting.periodclosing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Period Closing Log',
                'verbose_name_plural': 'Period Closing Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['period_closing', 'action'], name='accounting__period__750bc7_idx'), models.Index(fields=['user', 'timestamp'], name='accounting__user_id_58e17e_idx')],
            },
        ),
    ]
