# Generated by Django 5.2.6 on 2026-01-27 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_accountingentry_accounting_period_periodclosinglog'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('directories', '0005_contactperson'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectronicInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_type', models.CharField(choices=[('OUT', 'Исходящий (мы выставили)'), ('IN', 'Входящий (нам выставили)')], max_length=10, verbose_name='Invoice Type')),
                ('number', models.CharField(max_length=50, verbose_name='Number')),
                ('date', models.DateField(verbose_name='Date')),
                ('counterparty_tin', models.CharField(help_text='ИНН контрагента (ОБЯЗАТЕЛЬНО для E-Soliq!)', max_length=50, verbose_name='Counterparty TIN/INN')),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Base Amount')),
                ('vat_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='VAT Amount')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Total Amount')),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('SENT', 'Отправлен в E-Soliq'), ('ACCEPTED', 'Принят'), ('REJECTED', 'Отклонён'), ('CANCELLED', 'Отменён')], default='DRAFT', max_length=20, verbose_name='Status')),
                ('esoliq_uuid', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='E-Soliq UUID')),
                ('esoliq_sent_at', models.DateTimeField(blank=True, null=True)),
                ('esoliq_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('esoliq_rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Electronic Invoice (E-Soliq)',
                'verbose_name_plural': 'Electronic Invoices (E-Soliq)',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ESoliqIntegrationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('SEND_INVOICE', 'Отправка СФ'), ('CHECK_STATUS', 'Проверка статуса'), ('CANCEL_INVOICE', 'Отмена СФ'), ('GET_INVOICES', 'Получение списка СФ'), ('SUBMIT_DECLARATION', 'Подача декларации')], max_length=30, verbose_name='Action')),
                ('request_data', models.JSONField(default=dict)),
                ('response_data', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('SUCCESS', 'Успешно'), ('ERROR', 'Ошибка'), ('PENDING', 'В процессе')], max_length=20, verbose_name='Status')),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'E-Soliq Integration Log',
                'verbose_name_plural': 'E-Soliq Integration Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VATDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(verbose_name='Period (YYYY-MM-01)')),
                ('total_output_vat', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total Output VAT')),
                ('total_input_vat', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total Input VAT')),
                ('vat_payable', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='VAT Payable')),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('CALCULATED', 'Рассчитана'), ('SUBMITTED', 'Подана'), ('ACCEPTED', 'Принята')], default='DRAFT', max_length=20, verbose_name='Status')),
                ('submitted_date', models.DateField(blank=True, null=True)),
                ('esoliq_submission_id', models.CharField(blank=True, max_length=100, null=True)),
                ('esoliq_status', models.CharField(blank=True, max_length=50, null=True)),
                ('esoliq_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('esoliq_rejection_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'VAT Declaration (Monthly)',
                'verbose_name_plural': 'VAT Declarations (Monthly)',
                'ordering': ['-period'],
            },
        ),
        migrations.RemoveIndex(
            model_name='vattransaction',
            name='accounting__date_bc47d0_idx',
        ),
        migrations.AlterField(
            model_name='vatrate',
            name='code',
            field=models.CharField(help_text="e.g., '12%', '0%'", max_length=20, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='vatrate',
            name='rate',
            field=models.DecimalField(decimal_places=2, help_text='e.g., 12.00 for 12%', max_digits=5, verbose_name='Rate'),
        ),
        migrations.AlterField(
            model_name='vattransaction',
            name='base_amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Base Amount'),
        ),
        migrations.AlterField(
            model_name='vattransaction',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='vattransaction',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vattransaction',
            name='period',
            field=models.DateField(verbose_name='Period (YYYY-MM-01)'),
        ),
        migrations.AlterField(
            model_name='vattransaction',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Total Amount'),
        ),
        migrations.AlterField(
            model_name='vattransaction',
            name='vat_type',
            field=models.CharField(choices=[('INPUT', 'Входящий НДС (к зачёту)'), ('OUTPUT', 'Исходящий НДС (к уплате)')], max_length=10, verbose_name='VAT Type'),
        ),
        migrations.AddField(
            model_name='electronicinvoice',
            name='counterparty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='electronic_invoices', to='directories.counterparty'),
        ),
        migrations.AddField(
            model_name='electronicinvoice',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_einvoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='electronicinvoice',
            name='related_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='electronicinvoice',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electronic_invoices', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='electronicinvoice',
            name='vat_rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='electronic_invoices', to='accounting.vatrate'),
        ),
        migrations.AddField(
            model_name='electronicinvoice',
            name='vat_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_invoice', to='accounting.vattransaction'),
        ),
        migrations.AddField(
            model_name='vattransaction',
            name='electronic_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vat_transactions', to='accounting.electronicinvoice'),
        ),
        migrations.AddIndex(
            model_name='vattransaction',
            index=models.Index(fields=['electronic_invoice'], name='accounting__electro_677221_idx'),
        ),
        migrations.AddField(
            model_name='esoliqintegrationlog',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integration_logs', to='accounting.electronicinvoice'),
        ),
        migrations.AddField(
            model_name='esoliqintegrationlog',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='vatdeclaration',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vatdeclaration',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vat_declarations', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='electronicinvoice',
            index=models.Index(fields=['tenant', 'status', 'date'], name='accounting__tenant__232b0e_idx'),
        ),
        migrations.AddIndex(
            model_name='electronicinvoice',
            index=models.Index(fields=['counterparty', 'date'], name='accounting__counter_6e7e55_idx'),
        ),
        migrations.AddIndex(
            model_name='electronicinvoice',
            index=models.Index(fields=['esoliq_uuid'], name='accounting__esoliq__0d2242_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='electronicinvoice',
            unique_together={('tenant', 'invoice_type', 'number', 'date')},
        ),
        migrations.AddIndex(
            model_name='esoliqintegrationlog',
            index=models.Index(fields=['tenant', 'action', 'status'], name='accounting__tenant__dee72c_idx'),
        ),
        migrations.AddIndex(
            model_name='esoliqintegrationlog',
            index=models.Index(fields=['invoice'], name='accounting__invoice_fc5804_idx'),
        ),
        migrations.AddIndex(
            model_name='vatdeclaration',
            index=models.Index(fields=['tenant', 'status'], name='accounting__tenant__b89695_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vatdeclaration',
            unique_together={('tenant', 'period')},
        ),
    ]
