# Generated by Django 5.2.6 on 2026-01-27 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_electronicinvoice_esoliqintegrationlog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electronicinvoice',
            name='invoice_type',
            field=models.CharField(choices=[('OUT', 'Реализация (Sale)'), ('IN', 'Поступление (Purchase)'), ('RETURN_OUT', 'Возврат покупателю (Return Out)'), ('RETURN_IN', 'Возврат от поставщика (Return In)'), ('ADJUSTMENT', 'Корректировка (Adjustment)'), ('EXPORT', 'Экспорт (Export)'), ('AGENT', 'Агентский (Agent)')], max_length=20, verbose_name='Invoice Type'),
        ),
        migrations.AlterField(
            model_name='electronicinvoice',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Черновик'), ('SENT', 'Отправлен в E-Soliq'), ('ACCEPTED', 'Принят (Signed)'), ('REJECTED', 'Отклонён (Rejected)'), ('CANCELLED', 'Отменён (Cancelled)'), ('ERROR', 'Ошибка (Error)')], default='DRAFT', max_length=20, verbose_name='Status'),
        ),
    ]
