# Generated by Django 5.2.6 on 2026-01-29 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_alter_electronicinvoice_invoice_type_and_more'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_valuation_method', models.CharField(choices=[('FIFO', 'First In First Out (FIFO)'), ('AVG', 'Weighted Average'), ('LIFO', 'Last In First Out (LIFO)')], default='FIFO', help_text='Метод оценки товаров при списании', max_length=10, verbose_name='Stock Valuation Method')),
                ('effective_from', models.DateField(verbose_name='Effective From')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accounting_policy', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Accounting Policy',
                'verbose_name_plural': 'Accounting Policies',
            },
        ),
        migrations.CreateModel(
            name='AccountingPolicyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valuation_method', models.CharField(choices=[('FIFO', 'First In First Out (FIFO)'), ('AVG', 'Weighted Average'), ('LIFO', 'Last In First Out (LIFO)')], max_length=10, verbose_name='Valuation Method')),
                ('effective_from', models.DateField(verbose_name='Effective From')),
                ('effective_to', models.DateField(blank=True, help_text='NULL = still active', null=True, verbose_name='Effective To')),
                ('changed_by', models.CharField(blank=True, max_length=255, verbose_name='Changed By')),
                ('change_reason', models.TextField(blank=True, verbose_name='Reason for Change')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_history', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Accounting Policy History',
                'verbose_name_plural': 'Accounting Policy History',
                'ordering': ['-effective_from'],
                'indexes': [models.Index(fields=['tenant', 'effective_from'], name='accounting__tenant__19d8f4_idx')],
            },
        ),
    ]
