# Generated by Django 5.2.6 on 2026-02-07 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_accountingpolicy_accountingpolicyhistory'),
        ('tenants', '0002_permission_rolepermission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='Number')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
                ('amount', models.DecimalField(decimal_places=2, default=0, help_text='Sum of amounts (informational)', max_digits=15, verbose_name='Amount')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_operations', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Operation',
                'verbose_name_plural': 'Operations',
                'ordering': ['-date', '-created_at'],
                'unique_together': {('tenant', 'number')},
            },
        ),
    ]
