# Generated by Django 5.2.6 on 2026-02-09 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_operation'),
        ('directories', '0009_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingentry',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='directories.contract'),
        ),
        migrations.AddField(
            model_name='accountingentry',
            name='counterparty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='directories.counterparty'),
        ),
    ]
