# Generated by Django 5.2.6 on 2026-02-09 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_accountingentry_contract_and_more'),
        ('directories', '0010_department_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingentry',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='directories.department'),
        ),
        migrations.AddField(
            model_name='accountingentry',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='directories.employee'),
        ),
        migrations.AddField(
            model_name='accountingentry',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='directories.item'),
        ),
        migrations.AddField(
            model_name='accountingentry',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='directories.project'),
        ),
        migrations.AddField(
            model_name='accountingentry',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=0, help_text='For quantitative accounting (41, 10, 43)', max_digits=15, verbose_name='Quantity'),
        ),
        migrations.AddField(
            model_name='accountingentry',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='directories.warehouse'),
        ),
    ]
