# Generated by Django 5.2.6 on 2026-02-11 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_accountingentry_department_accountingentry_employee_and_more'),
        ('directories', '0011_cashflowitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingentry',
            name='cash_flow_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='directories.cashflowitem'),
        ),
    ]
